### ISSUE TITLE
Compatibility with spaCy version 2.3.2

### ISSUE THREAD

**Issue by igorjar** [huspacy/huspacy#15]
Hi there,

After installing as instructed:
`pip install https://github.com/oroszgy/spacy-hungarian-models/releases/download/hu_core_ud_lg-0.3.1/hu_core_ud_lg-0.3.1-py3-none-any.whl ` 

and loading the model the following warning is received:

```
 ....\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'hu_core_ud_lg' (0.3.1) requires spaCy v2.1 and is incompatible with the current spaCy version (2.3.2). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
```

Running: `python -m spacy validate` outputs:

 ```
PS D:\-ji\python>  python -m spacy validate
✔ Loaded compatibility table

====================== Installed models (spaCy v2.3.2) ======================
ℹ spaCy installation:
...\lib\site-packages\spacy

No models found in your current environment.
```

Can I ignore the above warning?

The time needed to call the `load()` method (`nlp = hu_core_ud_lg.load()`) varies from moment to moment from 6 seconds to 26 seconds, typically between 18s and 24s.

Is this speed normal or due to a combatilibilty issue?

Thanks!

**Comment by oroszgy** [comment]
Hi, thanks for the detailed report. Will look into the problem soon. 

Anyway, the loading time looks fine.
