### ISSUE TITLE
Spacy lemmatizer does not work with numbers as expected

### ISSUE THREAD

**Issue by gaborstats** [huspacy/huspacy#16]
Kedves György, észrevettem, h a spacy nem mindíg jól lemmatizálja a (betűvel kiírt) számokat. Íme egy példa:

```
import spacy
import hu_core_ud_lg
import pandas as pd

nlp = hu_core_ud_lg.load() # 2-3 perc

a = "nyolcvanöt"
b = "nyolcvanhat"
c = "nyolcvanhét" 
d = [a, b, c] 
  
df = pd.DataFrame(d, columns = ['datum']) 

output_lemma = []

for i in df.datum:
    mondat = ""
    doc = nlp(i)
    newtext = [(tok.lemma_, tok.is_title) for tok in doc]
    mondat = ' '.join([tok[0].title() if tok[1] == 1 else tok[0] for tok in newtext])
    output_lemma.append(mondat)

output_lemma 
['nyolcvan', 'nyolcvanh', 'nyolcvanhét']
```

Új vagyok a githubon, de nagyon szívesen segítenék a csomag fejlesztésében. Meg tudnád kérlek mondani, h ez reális nehézségű projekt lenne egy kezdő számára, vagy inkább érdemes előbb egy egyszerűbb feladat után néznem? 
Előre is nagyon köszönöm a válaszod!

**Comment by oroszgy** [comment]
Kedves Gabor, koszonom az eszrevetelt!

A lemmatizalast egy statisztikai elemzo modul (`lemmy`) vegzi, igy a hiba javitasahoz ket ut vezethet. 

1) A legegyszerubb talab egy utofeldolgozo lepes lenne a spacy pipelineba, ami ismeri a leggyakoribb szavak szotovet. 
2) Ha tudnak kesziteni nagyobb meretu, UD PoS cimkezett korpuszt, akkor erdemes lenne ujratanitani a `lemmy`-t.

Ha az 1) utat valasztod, az szerintem realis idoben, megoldhato lenne. Ha tenyleg lenne idod segiteni, akkor folytassuk emailben: gyorgy@orosz.link

**Comment by oroszgy** [comment]
Az spacy 3.x kompatibilis verziok ugyesebben lemmatizalnak, remelem ezeken az eseteken is tudtunk segiteni.
