### ISSUE TITLE
Does this model support fine-grained UD features?

### ISSUE THREAD

**Issue by dlazesz** [huspacy/huspacy#3]
In SpaCy one can access the fine-grained UD tags by the **tag_** attribute (see [documentation](https://spacy.io/api/token)). In this model it only repeats the value of **pos_**.

Is there any chance to get the CoNLL-U style FEATS from the tagged data for Hungarian?

**Comment by oroszgy** [comment]
Unfortunately, it is not implemented yet, but to be planned.

**Comment by oroszgy** [comment]
Update: spacy 3.x compatibility is in the works, meanings fine-grained UD tags are being supported in the next releases/

**Comment by oroszgy** [comment]
As with the new releases huspacy now support morph features.
