### ISSUE TITLE
Inkompatibilitás

### ISSUE THREAD

**Issue by VamperAta** [huspacy/huspacy#46]
Sajnos a kód (huspacy) és a nagy model(hu-core-news-lg) más spacy verziót kíván, és nincs közös halmazuk. A huspacy régebbi spacyt kíván, mint a model. Nem találtam megoldást az inkompatibilitás feloldására. Ebben kérnék segítséget.

Köszönettel !
Attila

**Comment by oroszgy** [comment]
Kedves Attila,

köszönjük a hiba jelzését. A probléma valóban fennáll, igyekszünk mihamarabb javítani. 

Addig is, ha `pip`-pel telepíted utólag a modellt a környezetedbe, valószínűleg működni fog: `!pip install https://huggingface.co/huspacy/hu_core_news_lg/resolve/main/hu_core_news_lg-any-py3-none-any.whl`
