### ISSUE TITLE
Hosszú szövegek feldolgozása

### ISSUE THREAD

**Issue by uveges** [huspacy/huspacy#54]
**Hiba leírása**
A `hu_core_news_trf` modellt használva, amennyiben az input 512 tokennél hosszabb, az elemzés hibaüzenettel megáll.

**Hiba előidézése**

Az alábbi Colab notebook szemléltei a hibát: 
https://colab.research.google.com/drive/1Z6BLO2RYssRQmvdPo66YHSReXFtDPmR0#scrollTo=o72kt1cYbVxD

A problémás szöveget közvetlenül a `huBERT`-nek átadva tokenizálásra úgy tűnik, hogy az 512 feletti tokenek simán "csonkolódnak", a probléma nem jelentkezik.

Hasnoló lehet: https://github.com/explosion/spaCy/issues/7891

**Elvárt működés**
Az 512 token feletti részt a modellnek figyelmen kívül kellene hagynia.

**További kontextus**

**Comment by oroszgy** [comment]
This might be related: https://github.com/explosion/spaCy/issues/6939

**Comment by oroszgy** [comment]
Managed to reproduce the bug: https://colab.research.google.com/drive/1_zF0H0-TdV1ynNkH8Afs6jiEE2ZyWqR6?usp=sharing#scrollTo=OMd4CXjvnwDe

**Comment by oroszgy** [comment]
This is now fixed as the new model is out: https://huggingface.co/huspacy/hu_core_news_trf
