### ISSUE TITLE
Mismatch between moduel version and models downloaded (Forced upgrade spacy 3.5 > 3.6)

### ISSUE THREAD

**Issue by astuanax** [huspacy/huspacy#60]
**Describe the bug**
The download facility downloads the wrong version of the models.
The installation is spacy 3.5.4, huspacy 0.9 (with hu_core_news_lg-v3.5.2)
When installing since today, spacy is uninstalled and replaced with 3.6 wich isn't compatible with the other models we have and use. 

**To Reproduce**
pipenv install spacy = "==3.5.4"
pipenv install huspacy = "*"

Then we run this code:
pipenv run python -c "import huspacy; huspacy.download()"

**Expected behavior**
Install corresponding version of the models.
Provide a way to set the version in the download function, even though this should really match the necessary versions. 

**Additional context**
We have encountered this since today, not sure how this happens as the 0.9 version doesn't  seem to have 3.6.
Here is someoutput from the pipenv instalation:

Installing collected packages: pl-core-news-lg
Successfully installed pl-core-news-lg-3.5.0
 ✔ Download and installation successful
 You can now load the package via spacy.load('pl_core_news_lg')
==>  Loading .env environment variables...
     Collecting hu-core-news-lg==any
  Downloading https://huggingface.co/huspacy/hu_core_news_lg/resolve/main/hu_core_news_lg-any-py3-none-any.whl (401.4 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 401.4/401.4 MB 3.7 MB/s eta 0:00:00
 Collecting spacy<3.7.0,>=3.6.0 (from hu-core-news-lg==any)
  Obtaining dependency information for spacy<3.7.0,>=3.6.0 from https://files.pythonhosted.org/packages/9a/7d/36cab023e0dd65bc2144137f3377481e07f93ead8abfa0be28702f1430e4/spacy-3.6.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata

Downloading spacy-3.6.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (6.7 MB)
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.7/6.7 MB 80.4 MB/s eta 0:00:00
 Installing collected packages: spacy, hu-core-news-lg
   Attempting uninstall: spacy
   Found existing installation: spacy 3.5.4
   Uninstalling spacy-3.5.4:
   Successfully uninstalled spacy-3.5.4

==> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
Successfully installed hu-core-news-lg-3.6.0 spacy-3.6.1
==>  da-core-news-lg 3.5.0 requires spacy<3.6.0,>=3.5.0, but you have spacy 3.6.1 which is incompatible.

**Comment by oroszgy** [comment]
Hi @astuanax, thanks for the report! 

This could be due to the fact, that new spacy 3.6 compatible models are already released, but the `huspacy` package is not yet updated. Will do that soon, up until then, you can still used older models as well: `huspacy.download("hu_core_news_lg", "3.5.2")`

**Comment by oroszgy** [comment]
@astuanax I've added a warning message when the model to be downloaded is not compatible with the spacy installed. This does not solves your problem completely, but I'd rather recommend to download/install the model with your package manager using an exact version, for example: `pip install https://huggingface.co/huspacy/hu_core_news_lg/resolve/v3.5.2/hu_core_news_lg-any-py3-none-any.whl`
