### ISSUE TITLE
Newline characters are processed as tokens

### ISSUE THREAD

**Issue by skrbog** [huspacy/huspacy#68]
**Describe the bug**
While discovering Huspacy, I encountered the following tokenization anomalies:
1.) Newline characters count as separate tokens. This also means that they appear to have an own processing result. However, their results are not consistent. For	example, in some cases the POS-tag is VERB, in some other cases NOUN, or ADJ, or even X. It seems to be quite random, I haven't discovered any regularity yet.
2.) When there are more than one newline characters in succession, then they are interpreted as one token (e. g. "\n\n\n" is one token).
3.) Every newline character is tokenized, either it's on the end of the file or inside the text. Also, as I use txt files as source for texts to be analyzed, there is a newline in every file on the end by default.

**To Reproduce**
1. With file as source:
```
file = open("somefile.txt")
txt = file.read()
file.close()
nlp = hu_core_news_lg.load()
doc = nlp(txt)
for token in doc:
	print(token.text + '\t' + token.lemma_ + '\t' + token.pos_)
```
2. With string as source:
```
txt = "Elmentem sétálni. \n\n\n Sajnos tíz percen belül\n eleredt az eső.\n"
nlp = hu_core_news_lg.load()
doc = nlp(txt)
for token in doc:
	print(token.text + '\t' + token.lemma_ + '\t' + token.pos_)
```

**Expected behavior**
I think the newlines should't be recognised as tokens at all, or at least they should't go further into the pipeline to be processed. If they do have to be processed, then they should get a consistent result.

**Additional context**
Sorry if this is a feature and it's intentional that it works the way it does now. Is there any reason why this could come in handy? (I can imagine there are some usecases I couldn't think of.)

Thank you in advance!

**Comment by oroszgy** [comment]
As per [spaCy's tokenizer](https://spacy.io/usage/linguistic-features#tokenization) this is the expected behavior in order to make the original text reproducible. You can filter whitespaces with the `is_space` attribute:

```python
txt = "Elmentem sétálni. \n\n\n Sajnos tíz percen belül\n eleredt az eső.\n"
nlp = hu_core_news_lg.load()
doc = nlp(txt)
for token in doc:
    if not token.is_space:
	print(token.text + '\t' + token.lemma_ + '\t' + token.pos_)
```

**Comment by skrbog** [comment]
Oh, I see, thank you!
