### ISSUE TITLE
Can't download language model: ERROR: Invalid requirement: 'hu-core-news-lg==any'

### ISSUE THREAD

**Issue by atesz77** [huspacy/huspacy#69]
**Describe the bug**
I can't download the language model with pip, as described in the main page.

Error shows after the command:
ERROR: Invalid requirement: 'hu-core-news-lg==any': Expected end or semicolon (after name and no valid version specifier)
    hu-core-news-lg==any

**To Reproduce**
1. pip install https://huggingface.co/huspacy/hu_core_news_lg/resolve/main/hu_core_news_lg-any-py3-none-any.whl

**Expected behavior**
Package installed.

**Additional context**
Python version: Python 3.12.6
Pip version: 24.2
Spacy version: 3.7.6

It does not work either with code (huspacy version: 0.11.0):
```
import huspacy
huspacy.download("hu_core_news_lg")
```

Thank you for your help!

**Comment by schubaa-yahoo-com** [comment]
Same problem. I have already written it in an email, as well. Thanks in advance.

**Comment by schubaa-yahoo-com** [comment]
Thanks to the HuSpaCy team, I received answer to my email. The solution (hopefully temporarily) is to downgrade pip to 23.3.2. Tested and it works.

**Comment by atesz77** [comment]
> Thanks to the HuSpaCy team, I received answer to my email. The solution (hopefully temporarily) is to downgrade pip to 23.3.2. Tested and it works.

Thank you for your help. 
This worked for me too, but I hope they will fix it in the future.

**Comment by oroszgy** [comment]
This issue is related to this upstream one: https://github.com/explosion/spaCy/issues/13599
