### ISSUE TITLE
The speed of processing of hu_core_news_trf is slow.

### ISSUE THREAD

**Issue by Dbgsaoge** [huspacy/huspacy#73]
**Is your feature request related to a problem? Please describe.**
I want to use hu_core_news_trf to do part-of-speech statistics for each sample sentence, but at a much slower pace than using nltk. I want to know what the problem is.

**Describe the solution you'd like**
Maybe some improvement about code

**Describe alternatives you've considered**

**Additional context**
My function is following:

def pos_tagging(input_str: str) -> list:

    doc = nlp(input_str)
    total_tokens = len(doc)
    
    if total_tokens < 20:
        return
    
    Blank_num_ratio = random.choice([0.05, 0.08, 0.1, 0.12])
    Blank_num = int(total_tokens * Blank_num_ratio) if int(total_tokens * Blank_num_ratio) < 20 else 20
    
    # Ratio: N:A:V:D:X = 5 : 3 : 1 : 0.5 : 0.5
    Token_Nouns = []
    Token_Adj = []
    Token_Verb = []
    Token_Det = []
    Token_X = []
    
    T_POS = []
    
    seen = set() # 跳过重复词
    for token in doc:
        T_POS.append(token.pos_)
        if token.pos_ in ['NOUN', 'PROPN'] and token.text not in seen:
            Token_Nouns.append(token.text)
            seen.add(token.text)
        elif token.pos_ in ['ADJ', 'ADV'] and token.text not in seen:
            Token_Adj.append(token.text)
            seen.add(token.text)
        elif token.pos_ in ['VERB'] and token.text not in seen:
            Token_Verb.append(token.text)
            seen.add(token.text)
        elif token.pos_ in ['DET'] and token.text not in seen:
            Token_Det.append(token.text)
            seen.add(token.text)
        elif token.pos_ in ['X'] and token.text not in seen:
            Token_X.append(token.text)
            seen.add(token.text)

    np.random.shuffle(Token_Nouns)
    np.random.shuffle(Token_Adj)
    np.random.shuffle(Token_Verb)
    np.random.shuffle(Token_Det)
    np.random.shuffle(Token_X)
    
    Token_Nouns = Token_Nouns[:int(Blank_num*0.5)+1]
    Token_Adj = Token_Adj[:int(Blank_num*0.3)+1]
    Token_Verb = Token_Verb[:int(Blank_num*0.1)+1]
    Token_Det = Token_Det[:int(Blank_num*0.05)+1]
    Token_X = Token_X[:int(Blank_num*0.05)+1]
    
    Token = Token_Nouns + Token_Adj + Token_Verb + Token_Det + Token_X
    
    return Token

**Comment by oroszgy** [comment]
Sorry, but this looks like spam to me.

**Comment by Dbgsaoge** [comment]
Sorry, maybe I should recheck it. When I use hu_core_news_trf to get token_pos_ on the GPU, it is very slow (taking about 2 hours), even though my text corpus isn't that large. But when I use NLTK, it only takes 10 minutes.
